# Site settings
title: Bring Developer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://developer.bring.com" # the base hostname & protocol for your site
permalink: /blog/:title/

# RAML settings
raml_08_map:
  api/shipping-guide/api.raml:
    target: api/shipping-guide/index.html
    sort_order: 11
    hide_nav: true
  api/pickup-point/api.raml:
    target: api/pickup-point/index.html
    sort_order: 20
  api/booking/api.raml:
    target: api/booking/index.html
    sort_order: 40
  api/reports/api.raml:
    target: api/reports/index.html
    sort_order: 110
  api/invoice/api.raml:
    target: api/invoice/index.html
    sort_order: 120
  api/postal-code/api.raml:
    target: api/postal-code/index.html
    sort_order: 30
  api/order-management/api.raml:
    target: api/order-management/index.html
    sort_order: 130
  api/warehousing/api.raml:
    target: api/warehousing/index.html
    sort_order: 140
  api/modify-delivery/api.raml:
    target: api/modify-delivery/index.html
    sort_order: 80

raml_10_map:
  api/shipping-guide_2/api.raml:
    target: api/shipping-guide_2/index.html
    sort_order: 10
  api/shipment/api.raml:
    target: api/shipment/index.html
    sort_order: 50
  api/tracking/api.raml:
    target: api/tracking/index.html
    sort_order: 90
  api/event-cast/api.raml:
    target: api/event-cast/index.html
    sort_order: 100

# Build settings
plugins:
- jekyll-paginate
- jekyll-archives

paginate: 10
paginate_path: /blog/page/:num # default is page:num

jekyll-archives:
  enabled: [categories]
  layouts:
    category: archives/category
  permalinks:
    category: '/blog/category/:name/'

markdown: kramdown
kramdown:
  input: GFM

sass:
  style: compressed

exclude: [Rakefile, Gemfile, Gemfile.lock, README.md, bower.json, developer-site.iml, node_modules, LICENSE, package.json, yarn.lock, Jenkinsfile]
