name: developer-site
jettypath: developer-site-jetty
internal_check_type: statuscode
external_url_skip_version_check: true
healthcheck: jetty
slack_notifications: [api]

environments:
  production:
    selvdrift_layout: true
    bigip_frontend: true
    hosts: [posap394.bd.bring.no, posap395.bd.bring.no]
    port: 8040
    user: bring
    prefix: /var/apps/developer/
    service_name: developer
    start_command: sudo service developer start
    stop_command: sudo service developer stop
    external_url: http://developer.bring.com/revision.txt
    internal_url: /
    production_environment: true
  qa:
    selvdrift_layout: true
    bigip_frontend: true
    hosts: [posap402.bd.bring.no, posap403.bd.bring.no]
    port: 8540
    user: bring
    prefix: /var/apps/developer_qa/
    service_name: developer_qa
    start_command: sudo service developer_qa start
    stop_command: sudo service developer_qa stop
    external_url: http://developer:developer@developer.qa.bring.com/revision.txt
    internal_url: /
    http_auth_user: developer
    http_auth_password: developer
    production_environment: false
  test:
    selvdrift_layout: true
    bigip_frontend: false
    hosts: [alt-daran.bd.bring.no]
    port: 8040
    user: bring
    prefix: /var/apps/developer_test/
    service_name: developer_test
    start_command: sudo service developer_test start
    stop_command: sudo service developer_test stop
    external_url: http://developer:developer@developer.test.bring.com/revision.txt
    internal_url: /
    http_auth_user: developer
    http_auth_password: developer
    production_environment: false
